/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Fri Jun 17 21:18:23 GMT 2016
 */

package tp2;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class Server_ESTest_scaffolding {

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);

  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "tp2.Server"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init(); 
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("java.vm.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.specification.version", "1.8"); 
            java.lang.System.setProperty("java.home", "/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre"); 
    java.lang.System.setProperty("user.dir", "/Users/alangonzalez/Desktop/TP2Testing/bin"); 
        java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("user.home", "/Users/alangonzalez"); 
                                        java.lang.System.setProperty("java.io.tmpdir", "/var/folders/kj/09kqw0t91bxgzxr48rzkm5dh0000gn/T/"); 
    java.lang.System.setProperty("awt.toolkit", "sun.lwawt.macosx.LWCToolkit"); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("file.separator", "/"); 
        java.lang.System.setProperty("java.awt.graphicsenv", "sun.awt.CGraphicsEnvironment"); 
    java.lang.System.setProperty("java.awt.printerjob", "sun.lwawt.macosx.CPrinterJob"); 
    java.lang.System.setProperty("java.class.path", "/var/folders/kj/09kqw0t91bxgzxr48rzkm5dh0000gn/T/EvoSuite_pathingJar3233269695062937412.jar"); 
    java.lang.System.setProperty("java.class.version", "52.0"); 
        java.lang.System.setProperty("java.endorsed.dirs", "/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/endorsed"); 
    java.lang.System.setProperty("java.ext.dirs", "/Users/alangonzalez/Library/Java/Extensions:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/ext:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java"); 
    java.lang.System.setProperty("java.library.path", "lib"); 
    java.lang.System.setProperty("java.runtime.name", "Java(TM) SE Runtime Environment"); 
    java.lang.System.setProperty("java.runtime.version", "1.8.0_65-b17"); 
    java.lang.System.setProperty("java.specification.name", "Java Platform API Specification"); 
    java.lang.System.setProperty("java.specification.vendor", "Oracle Corporation"); 
        java.lang.System.setProperty("java.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.vendor.url", "http://java.oracle.com/"); 
    java.lang.System.setProperty("java.version", "1.8.0_65"); 
    java.lang.System.setProperty("java.vm.info", "mixed mode"); 
    java.lang.System.setProperty("java.vm.name", "Java HotSpot(TM) 64-Bit Server VM"); 
    java.lang.System.setProperty("java.vm.specification.name", "Java Virtual Machine Specification"); 
    java.lang.System.setProperty("java.vm.specification.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.vm.specification.version", "1.8"); 
    java.lang.System.setProperty("java.vm.version", "25.65-b01"); 
    java.lang.System.setProperty("line.separator", "\n"); 
    java.lang.System.setProperty("os.arch", "x86_64"); 
    java.lang.System.setProperty("os.name", "Mac OS X"); 
    java.lang.System.setProperty("os.version", "10.11.4"); 
    java.lang.System.setProperty("path.separator", ":"); 
    java.lang.System.setProperty("user.country", "ES"); 
    java.lang.System.setProperty("user.language", "es"); 
    java.lang.System.setProperty("user.name", "alangonzalez"); 
    java.lang.System.setProperty("user.timezone", "America/Argentina/Cordoba"); 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(Server_ESTest_scaffolding.class.getClassLoader() ,
      "korat.finitization.impl.FieldDomain",
      "korat.finitization.impl.ClassDomain",
      "korat.testing.ITester",
      "tp2.StubTime",
      "korat.finitization.impl.PrimitiveTypeSet",
      "korat.finitization.IDoubleSet",
      "korat.instrumentation.IKoratTouchable",
      "tp2.ITime",
      "korat.finitization.IFinitization",
      "tp2.IPBan",
      "korat.finitization.impl.IntSet",
      "korat.finitization.IIntSet",
      "tp2.Node",
      "tp2.StrictlySortedSinglyLinkedList",
      "korat.finitization.impl.Finitization",
      "korat.finitization.IByteSet",
      "korat.finitization.impl.ArrayElementCVElem",
      "korat.instrumentation.IKoratArray",
      "korat.finitization.IArraySet",
      "korat.finitization.impl.ObjSet",
      "korat.finitization.IFloatSet",
      "tp2.Server",
      "korat.finitization.ILongSet",
      "korat.finitization.IFieldDomain",
      "tp2.RealTime",
      "tp2.Entry",
      "korat.finitization.impl.FinitizationFactory",
      "korat.finitization.IBooleanSet",
      "korat.finitization.impl.NullClassDomain",
      "tp2.IP",
      "korat.finitization.IFinitizationFactory",
      "korat.finitization.impl.StateSpace",
      "korat.finitization.impl.CVElem",
      "korat.finitization.IPrimitiveTypeSet",
      "korat.finitization.IObjSet",
      "korat.finitization.IClassDomain",
      "korat.finitization.IShortSet",
      "korat.utils.ReflectionUtils",
      "tp2.SinglyLinkedList"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(Server_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "tp2.Server",
      "korat.finitization.impl.FinitizationFactory",
      "tp2.SinglyLinkedList",
      "tp2.Entry",
      "tp2.StrictlySortedSinglyLinkedList",
      "tp2.Node",
      "tp2.RealTime",
      "tp2.IP",
      "tp2.IPBan",
      "korat.finitization.impl.Finitization",
      "korat.finitization.impl.ClassDomain",
      "korat.finitization.impl.NullClassDomain",
      "korat.utils.ReflectionUtils",
      "tp2.StubTime"
    );
  }
}
